# This file was generated by GoReleaser. DO NOT EDIT.
cask "rp1-beta" do
  version "0.7.0-beta.6"

  on_macos do
    on_intel do
      url "https://github.com/rp1-run/rp1/releases/download/v#{version}/rp1-darwin-amd64"
      sha256 "85b529738468d2ade8041a85d49318c9351ac15a83f62b5a0899190cc19de1d9"
      binary "rp1-darwin-amd64", target: "rp1"
    end
    on_arm do
      url "https://github.com/rp1-run/rp1/releases/download/v#{version}/rp1-darwin-arm64"
      sha256 "2f2e82cfe96a4b7a05f0a545a5d2ebb4e5375fb89900ccb567b14df0d41f2371"
      binary "rp1-darwin-arm64", target: "rp1"
    end
  end

  name "rp1-beta"
  desc "AI-assisted development workflows CLI (pre-release)"
  homepage "https://rp1.run"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "rp1",
    ]

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path] if OS.mac?
  end

  # No zap stanza required

end
