# This file was generated by GoReleaser. DO NOT EDIT.
cask "rp1-beta" do
  version "0.7.0-beta.8"

  on_macos do
    on_intel do
      url "https://github.com/rp1-run/rp1/releases/download/v#{version}/rp1-darwin-amd64"
      sha256 "300b03ba2bccb5885bb35f599b67ae851ca25256a564c52bd14d84ebb55c9adf"
      binary "rp1-darwin-amd64", target: "rp1"
    end
    on_arm do
      url "https://github.com/rp1-run/rp1/releases/download/v#{version}/rp1-darwin-arm64"
      sha256 "90b0d63505da150c300089a4ec7764c47330468e9cf7844222eac08fd6762aaa"
      binary "rp1-darwin-arm64", target: "rp1"
    end
  end

  name "rp1-beta"
  desc "AI-assisted development workflows CLI (pre-release)"
  homepage "https://rp1.run"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "rp1",
    ]

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path] if OS.mac?
    puts "Run 'rp1 install' to set up plugins for Claude Code, OpenCode, and Codex."
  end

  # No zap stanza required

end
