# This file was generated by GoReleaser. DO NOT EDIT.
cask "rp1-beta" do
  version "0.7.0-beta.4"

  on_macos do
    on_intel do
      url "https://github.com/rp1-run/rp1/releases/download/v#{version}/rp1-darwin-amd64"
      sha256 "0e3b7778d1f6bde73011c1806b0c2db2de24e0731eedf4baa59f09e530f2b26d"
      binary "rp1-darwin-amd64", target: "rp1"
    end
    on_arm do
      url "https://github.com/rp1-run/rp1/releases/download/v#{version}/rp1-darwin-arm64"
      sha256 "7999f8e7d4113ea60bda7841e9be31c77e624f6c2a9ba3e134804340240170ce"
      binary "rp1-darwin-arm64", target: "rp1"
    end
  end

  name "rp1-beta"
  desc "AI-assisted development workflows CLI (pre-release)"
  homepage "https://rp1.run"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "rp1",
    ]

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path] if OS.mac?
    system_command "#{staged_path}/rp1", args: ["install"],
      print_stderr: false
  end

  # No zap stanza required

end
