# This file was generated by GoReleaser. DO NOT EDIT.
cask "rp1" do
  name "rp1"
  desc "AI-assisted development workflows CLI"
  homepage "https://rp1.run"
  version "0.4.8"

  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    on_intel do
      url "https://github.com/rp1-run/rp1/releases/download/v#{version}/rp1-darwin-amd64"
      sha256 "393ab4dad4bde0d0f78fcf978391d96cebe4898ed952974e9410cb568695ce59"
      binary "rp1-darwin-amd64", target: "rp1"
    end
    on_arm do
      url "https://github.com/rp1-run/rp1/releases/download/v#{version}/rp1-darwin-arm64"
      sha256 "a8dcad94392ea314c45aa7ded36fa60812fddea5666c9456d15ec69e293f10ee"
      binary "rp1-darwin-arm64", target: "rp1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rp1-run/rp1/releases/download/v#{version}/rp1-linux-amd64"
      sha256 "646b5821a9bdd43e368b1f3fe9a077ef0b6e048c23dea3b1532ae0fea199ab88"
      binary "rp1-linux-amd64", target: "rp1"
    end
    on_arm do
      url "https://github.com/rp1-run/rp1/releases/download/v#{version}/rp1-linux-arm64"
      sha256 "2001af86716ff6145c3e9015568622339521d49341ade295338045402c6d7e40"
      binary "rp1-linux-arm64", target: "rp1"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path] if OS.mac?
  end

  # No zap stanza required
end
