# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rp1 < Formula
  desc "AI-assisted development workflows CLI"
  homepage "https://rp1.run"
  version "6.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rp1-run/rp1/releases/download/v6.0.1/rp1-darwin-amd64"
      sha256 "38b60e322b67668269cedfe072efd8102f0d84ee8a1910c5a13a0fba62604478"

      def install
        bin.install "rp1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rp1-run/rp1/releases/download/v6.0.1/rp1-darwin-arm64"
      sha256 "6d7131b6e6797a62bdc5ec9ab0ea421a14acb3272884e25237310cf9c5a49c6f"

      def install
        bin.install "rp1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rp1-run/rp1/releases/download/v6.0.1/rp1-linux-amd64"
      sha256 "0686a2661982c80e068313770d7d6cd00f7c60dc68f656af35d18fc0d2c7a0f1"
      def install
        bin.install "rp1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rp1-run/rp1/releases/download/v6.0.1/rp1-linux-arm64"
      sha256 "9a4636686bd4ef8a497479599e1962e8fa039d282e347441bd8d9c95173a1550"
      def install
        bin.install "rp1"
      end
    end
  end
end
